# Helper file, this playbook is not used inside the operator
# This playbook is useful to runnin locally for easy development
# Command: ansible-playbook -i playbook.yaml -vv
---
- hosts: localhost
  gather_facts: no
  vars:
    ansible_operator_meta:
      name: testpmd-manual1
      namespace: example-cnf
  tasks:
  - include_role:
      name: testpmd
    vars:
      privileged: true
      image: registry.redhat.io/openshift4/dpdk-base-rhel8:v4.6
      ethpeer_maclist:
        - e4:43:4b:4a:33:82
        - e4:43:4b:4a:33:83
      size: 1
      networks:
        - name: vhost1
          count: 1
        - name: vhost2
          count: 1
      skip_resource: true
